---
name: echo_rule
pack: stackstorm_training
enabled: true
trigger:
  type: core.st2.IntervalTimer
  unit: seconds
  delta: 15
action:
  ref: stackstorm_training.echo_action
  parameters:
    message: "Hello World"
