---
name: echo_rule
pack: stackstorm_training
enabled: true
trigger:
  type: "core.st2.webhook"
  parameters:
    url: "task-automation/db/oracle/add-datafile"
action:
  ref: stackstorm_training.echo_action
  parameters:
    message: "Hello World"
