---
name: echo_rule
pack: stackstorm_training
enabled: true
trigger:
  type: core.st2/IntervalTimer
  delta: 2
  unit: minutes
action:
  ref: stackstorm_training
  parameters:
    message: "Hello World"
